src/store/modules/auth.js
src/views/Login.vue

Took me an embarrassing amount of time to realize I named my store method `signup` instead of `signUp` 🤦‍♂️
Sign up form works now.

Fix sign up form typo

---

src/components/MatchCard.vue
src/components/PredictionChoiceDraw.vue
src/components/PredictionChoiceTeam.vue
src/views/Matches.vue

Add visual clues for prediction result + logic to disable predictions

---

src/components/MatchCard.vue
src/components/PredictionChoiceDraw.vue
src/components/TeamBadge.vue
tailwind.config.js

Fix class name and add missing classes to safelist

---

src/components/LeaderboardRanking.vue

preventing long names/emails from overflowing
*Now:*
*Prev:*

preventing long names/emails from overflowing

---

src/api/repositories/users.js
src/store/modules/users.js
src/views/UserProfile.vue

⚠️ You [need this code](https://github.com/dmbf29/predictor-api/pull/40/files) on your API in order to update a user
Two small bugs 🐛 
1. After update and when the profile page is refreshed, it looks like the current user is coming from the previously cached version or root auth version.
2. ~~No idea on how to pass a default value into the input~~

A user can update their display name

---

src/views/layouts/DefaultLayout.vue

This fixes the header to the top of the page.
The content scrolls within the main container of the DefaultLayout

Scroll content in default layout

---

src/api/repositories/users.js
src/components/LeaderboardCard.vue
src/components/LeaderboardRanking.vue
src/components/MatchCard.vue
src/components/MatchesGrouping.vue
src/components/_BaseLink.vue
src/store/modules/matches.js
src/store/modules/users.js
src/utils/helpers.js
src/views/Matches.vue

You need [this PR](https://github.com/dmbf29/predictor-api/pull/65) for this one to work.

Feature: show predictions from other users

---

src/components/MatchCard.vue

I'll leave it to you on which one you prefer. 
Original:
New Centered Version:

removed 'vs.' and centered the DRAW action

---

src/views/layouts/DefaultLayout.vue

Our desktop container got lost along the way somewhere. I was pretty nervous implementing this since i thought i might break some swiper things, but appears to be okay...
I just added a `div` around the `main`
```
<div class="flex justify-center w-full h-full">
```
then added a max-width on the `main`
```
max-w-screen-md
```

Added a div to center the content on desktop

---

src/components/NavBarRoutes.vue
src/components/TopNav.vue
src/views/Home.vue

Fixed the white nav bar and stop the icons on top from getting grayed out

navbar bg-color && grayed out icon

---

src/components/MatchCard.vue
src/components/PredictionSwiperCard.vue

based it on draws only happening when there's a groupId

Disable draw

---

src/components/TeamBadge.vue

Since the World Cup doesnt have badges (unlike the Euros), the flags we're getting displayed poorly:
So I put the background position to cover then align in the center:

zoomed into center of flag

---

package.json
src/components/CornerPoints.vue
src/components/FooterNav.vue
src/components/Header.vue
src/components/LeaderboardAction.vue
src/components/LeaderboardSubHeader.vue
src/components/MatchesSubHeader.vue
src/components/NavBarRoutes.vue
src/components/TopNav.vue
src/components/_BaseButton.vue
src/components/_BaseSpinner.vue
src/styles/_colors.scss
src/styles/_sizes.scss
src/styles/_typography.scss
src/views/layouts/DefaultLayout.vue
tailwind.config.js

This PR implements the following work:
- Fix media query size and add calc to fix deprecation warnings
- Add Tailwind JIT mode
- Tweak navigation styling (add name of menu item, colors, etc.)
- Other minor styling tweaks
Before | After
:-------------------------:|:-------------------------:

Styling tweaks (Navbar)

---

src/components/TeamBadge.vue
src/components/TopNav.vue
src/router/index.js
src/store/modules/auth.js
src/store/modules/competitions.js

- Remove hardcoded competition ID from route
- Fix missing dynamic class due to Tailwind JIT
Also slightly refactored the login logic to fetch the current competition upon login. The competition can also be forced via an ENV `VUE_APP_COMPETITION_ID`.

Fix hardcoded competition ID

---

src/components/PredictionSwiper.vue

This isn't perfect. But looked like a quick way to make it look marginally better. I couldn't actually replicate the problem in the browser properly. 
Before:
After:

quick fix to move buttons higher

---

src/components/TeamBadge.vue

Not sure when it switched from `incorrect` to `wrong`
Current:
Fix:

changed incorrect to wrong

---

src/components/MatchCard.vue

- Could make something fancier but kept it simple for now
- no top right Icon
- border-default (grey)
- no prediction was made text

Hide prediction card if no prediction was made #200

---

src/components/AnimatedArrow.vue
src/components/LeaderboardRankingsCard.vue
src/components/LeaderboardSubHeader.vue
src/store/modules/leaderboards.js
src/utils/request.js
src/views/ForgotPassword.vue
src/views/Home.vue
src/views/LeaderboardNew.vue
src/views/Login.vue
src/views/Predict.vue
src/views/Predictions.vue
src/views/Rankings.vue
src/views/ResetPassword.vue
src/views/Results.vue
src/views/UserProfile.vue
src/views/layouts/DefaultLayout.vue
src/views/layouts/SnapNavigationLayout.vue

This PR mainly implements a snap scroll behaviour to switch between leaderboards.
Other improvements added by this PR:
- Add tutorial for leaderboard swipe (state is saved in local storage so that it only shows up once)
- Add back button for user predictions
- Add progress bar whenever an API request is in progress to see if data is refreshing in the background
https://user-images.githubusercontent.com/34345789/204815216-f50e0d0f-46d2-4c98-bd0d-0d46eae90f6d.MP4

Add snap scroll switching of leaderboards

---

src/components/FooterNav.vue
src/components/LeaderboardAction.vue
src/components/PredictionSwiper.vue
src/components/SwipeTutorial.vue
src/router/index.js
src/store/modules/auth.js
src/views/LeaderboardNew.vue
src/views/Predict.vue
src/views/Results.vue
src/views/layouts/SnapNavigationLayout.vue

Some minor fixes that I've noticed while testing around:
- [Change `IntersectionObserver` threshold to make it feel more reactive](https://github.com/trouni/predictor-vue/pull/234/commits/224943433b003b993ab2574af9bd64782df692c7)
- [Fetch matches upon mounting the Results component](https://github.com/trouni/predictor-vue/pull/234/commits/6c991aee4aa583339c44140353ecdbd726724382) (the matches may be missing if the user does not visit the Predict page)
- [Reduce delay for tutorial start and hide on `touchstart` event](https://github.com/trouni/predictor-vue/pull/234/commits/ae2c7c7105be1c2bb5017795be76a1252f37f2bb) (not just click)
- [Increase footer's `z-index` to be on top of tutorial overlay](https://github.com/trouni/predictor-vue/pull/234/commits/0ae0014ecd35d7e093bdda92235a1b9365792e4 …

Fixing various minor issues

---

src/components/FooterNav.vue

I went to the TopNav component and just did the opposite in the FooterNav
Before
After

bottom mobiles navbar no longer showing up in desktop mode

---

src/components/LeaderboardRanking.vue
src/components/LeaderboardRankingsCard.vue
src/router/routes.js
src/views/Predictions.vue

This is another placeholder along with #248 for the results
Before and after (when no other members)
<p float='left'>
</p>
Before and after (when members)
<p float='left'>
</p>

Added a placeholder card for users when they haven't made any predictions

---

src/views/LeaderboardNew.vue
src/views/Rankings.vue

Two things fixed:
1. When you navigate away from the rankings/leaderboard page, it will return you to that same leaderboard when you return.
2. When you create a new leaderboard, it will take you to that newly created one (instead of the first one like it was doing originally).
Closes #256

Leaderboard current

---

src/store/modules/competitions.js
src/views/Login.vue
src/views/layouts/DefaultLayout.vue

There's an issue when we try to set the meta title from routes.js,I think the property is not in state yet when we try to grab it, 
`title: store.getters['competitions/currentCompetition']?.name,`
it is after the page loads, that's why it works properly on refresh. We'll need to investigate the flow of the route closer, but this temporary fix should work for now (we watch for title changes and grab it from the state after its available, not before)

Infinite Loading After login Fix

---

src/components/TeamBadge.vue

We were already using `border-6` on the draw component anyway (as you can see below)
<p float='left'>
</p>

made the border width thicker to see the prediction clearer

---

src/components/LeaderboardRankingsCard.vue
src/components/LeaderboardResults.vue

⚠️ This has big repercussions. In order for this to work, the [back-end PR](https://github.com/dmbf29/predictor-api/pull/121) needs to be merged as well.
Then in the front-end, we have access to all of the users. That way, if someone is ranked 12 but tied with the person who is 10th, we'll show them. And we also have access to the `currentUser`'s score and can display it if they're not in the top 10

showing all the users who have the same rank as the top 10

---

src/components/CompetitionsList.vue
src/components/Header.vue
src/router/routes.js
src/views/Competitions.vue
src/views/UserProfile.vue

⚠️ I'm merging this one into @Netsujr 's previous PR #263 so best to approve and merge this one first
changed all the titles to be the name of the competion which redirects to the profile page to the profile page (for now) where you can switch comepitions.

changed all the titles to be the name of the competion which redirects to the profile page

---

src/components/CompetitionsList.vue
src/components/Header.vue
src/router/routes.js
src/views/Competitions.vue
src/views/UserProfile.vue
src/views/layouts/DefaultLayout.vue

Before/After
- Why did we have it only for admins? Can add it back in if needed
- Made buttons column (can update further down the line)
- Clicking on a competition sets it as the currentCompetition in state, which fetches the correct data after navigation
- Past competitions (should these be clickable?, doesn't seem to break anything) have secondary style, ongoing have primary
- Maybe we can remove 'Euro Test' from BE? 
- Investigated the previous issue a little title deeper and fixed at the root, removed temporary fix. 
I realised the 2nd screenShot shows 'Copa America' in /profile. Title comes directly from meta now. Fallback is "Predictions"

Competition Buttons adjustment
