trouni/predictor-vue

babel.config.js
package.json
src/App.vue
src/components/_BaseButton.vue
src/components/_BaseIcon.vue
src/components/_BaseInputText.vue
src/components/_BaseLink.vue
src/components/_globals.js
src/main.js
src/plugins/fontawesome.js
src/styles/_animations.scss
src/styles/_colors.scss
src/styles/_fonts.scss
src/styles/_layers.scss
src/styles/_sizes.scss
src/styles/_typography.scss
src/styles/index.scss
src/views/Login.vue
yarn.lock

Feature: Setup base components

---

netlify.toml
package.json
src/components/MatchCard.vue
src/store/modules/competitions.js
src/store/modules/matches.js
src/views/Matches.vue
src/views/UserProfile.vue
yarn.lock

Added some logic code to fetch the matches and users from the API.

Add boilerplate code for fetching users and matches

---

src/components/FooterNav.vue
src/components/NavBarRoutes.vue
src/styles/_colors.scss
src/views/UserProfile.vue

Closes #14 
The Hamburger didn't seem to make much sense if we only have a user page and log out at this point. I think the user page and "hambuger more" is the same thing.  So i just defaulted on the user page and moved the log out to that page for now.

Footer Nav

---

src/components/LeaderboardRanking.vue
src/styles/_colors.scss
src/views/Leaderboards.vue

Closes #17 
Created a basic version of the row element

Leaderboard ranking

---

.github/workflows/lint.yml

Add linter to GitHub actions

---

src/components/FooterNav.vue
src/components/Header.vue

container was adding max width before but fixed to center things.
linter also helped some indentation things.

fixed the container classes since after adding tailwind

---

src/api/repositories/matches.js
src/components/MatchCard.vue
src/utils/request.js

Fix set prediction method

---

src/store/modules/auth.js
src/utils/request.js

Updating auth headers for each request

Fix authentication headers

---

src/router/routes.js
src/store/modules/leaderboards.js
src/views/Leaderboards.vue

So this works... but didn't want to take it further into the headers without double checking first. I based this off of previous code instead of following best practices

Leaderboards state

---

src/components/LeaderboardSubHeader.vue
src/store/modules/leaderboards.js
src/views/Leaderboards.vue

You can merge it directly once you've approved.
I have commented directly on some of the files to give contextual explanations. You can delete these comments.
Here are some documentation links that I recommend:
- [Computed Properties and Watchers](https://vuejs.org/v2/guide/computed.html) > definitely a must-read for Vue. `methods` are not reactive, you should be using computed properties whenever possible.
- [Reactivity](https://vuejs.org/v2/guide/reactivity.html) (especially the [Change Detection Caveats](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats), will prevent you some headaches in the future)
- [Vuex Getters](https://vuex.vuejs.org/guide/getters.html), but I would also browse through the Core Concepts of Vuex
I highly recommend reading the Vue and Vuex docs. …

Refactor to use Vuex store in component

---

src/components/Header.vue
src/components/LeaderboardSubHeader.vue
src/components/MatchesSubHeader.vue
src/router/routes.js
src/store/modules/leaderboards.js
src/views/Leaderboards.vue
src/views/layouts/DefaultLayout.vue

Closes #50 
Using selected Leaderboard to navigate pages. Still doesnt change the bottom div tho...

Leaderboards nav

---

src/api/repositories/leaderboards.js
src/components/LeaderboardAction.vue
src/components/LeaderboardActions.vue
src/components/ShareButton.vue
src/store/modules/leaderboards.js
src/styles/_colors.scss
src/views/LeaderboardNew.vue
src/views/Leaderboards.vue
src/views/layouts/DefaultLayout.vue

Still going to think how we add the + and share btns but the functionality is there

New leaderboard

---

src/router/routes.js
src/views/Login.vue

gave the signin/signup page a header and form labels

Sign in/up Header and Labels

---

src/components/LeaderboardSubHeader.vue
src/components/MatchesSubHeader.vue
src/store/modules/leaderboards.js
src/views/layouts/DefaultLayout.vue

Swipe to change leaderboards

---

src/components/PredictionSwiperCard.vue
src/views/layouts/DefaultLayout.vue
tailwind.config.js

Went a bit overboard with that lightning initially, don't think it matches. Plus there's already a lot going on.

Remove card glow

---

src/components/PredictionSwiper.vue
src/store/modules/matches.js
src/views/Leaderboards.vue
src/views/Matches.vue
src/views/PredictionsNew.vue

Resolves #98 
Speed up loading of pages by displaying data in Vuex store while the app is re-fetching the data.

Caching - Load data from store before fetching

---

.github/workflows/codeql-analysis.yml

Replacement for DeepCode to discover code vulnerabilities in PRs.

Add CodeQL action from GitHub

---

package.json
public/index.html
src/api/repositories/users.js
src/cloudinary.js
src/components/LeaderboardRanking.vue
src/constants/index.js
src/main.js
src/store/modules/users.js
src/utils/helpers.js
src/views/LeaderboardNew.vue
src/views/UserProfile.vue
src/views/layouts/DefaultLayout.vue
yarn.lock

⚠️  This needs [this API PR](https://github.com/dmbf29/predictor-api/pull/55) in order to get the user keys
I ended up adding more on this PR than I expected. However, a user can upload a photo and see their avatar on the Leaderboard Ranking page.
When no photo:
On click of Cloudinary trigger
After upload:
On leaderboard:
Whenever I go to the profile page for the first time, I'm not actually fetching the user. It's getting the user from the auth. But the auth doesn't seem to be using the actual fields from the API so we're missing `user.photoKey` 
So... even if you have a photo attached, the first time you see the profile page, you'll see the placeholder image

Cloudinary upload

---

src/views/UserProfile.vue

That way we can switch competitions from the profile page (only for admin users)

Add competition links to admin profiles

---

.env.development

Closes #65 
I misread your comment before. I didn't realize we put it in the config. i thought that that file might be git ignored.

cloudinary cloud name

---

src/components/LeaderboardActions.vue
src/components/ShareButton.vue

changed share->invite and add->new

---

src/components/LeaderboardCard.vue

sorting users by points

---

src/components/HomeStep.vue
src/views/Home.vue

made everything bigger for the landing page

---

src/api/repositories/leaderboards.js
src/components/ConfirmDelete.vue
src/components/LeaderboardAction.vue
src/components/LeaderboardActions.vue
src/store/modules/leaderboards.js

Closes #123 
Closes #66 
User can either delete an empty leaderboard or leave an existing one

Remove membership

---

src/App.vue
src/components/ConfirmButton.vue
src/components/PredictionSwiper.vue
src/components/PredictionSwiperCard.vue
src/components/PredictionSwiperStatus.vue
src/components/UndoButton.vue
src/components/_BaseIcon.vue
src/router/routes.js
src/store/index.js
src/store/modules/matches.js
src/views/Matches.vue
src/views/PredictionsNew.vue
src/views/layouts/DefaultLayout.vue
tailwind.config.js

Fixed the display issue and added a couple features to the swiper.

Add confirmation + Allow updating of predictions

---

src/components/FooterNav.vue
src/components/NavBarRoutes.vue

Tweak footer navbar styling

---

src/components/PredictionSwiper.vue
src/components/PredictionSwiperCard.vue

It was changing to the next match to early, it's now fixed.
Also fixed a display issue on desktop for the swiper.

Fix the team name's display right after pressing confirm

---

src/views/UserProfile.vue

small check feedback on when a username gets update

---

src/components/_BaseButton.vue
tailwind.config.js

Slightly changed button design to match the overall rounded design

Tweak button style

---

src/components/ConfirmButton.vue
src/components/PredictionSwiper.vue
src/components/UndoButton.vue
src/components/_BaseButton.vue
src/utils/helpers.js
src/views/Matches.vue
tailwind.config.js

Style swiper buttons and matches page

---

src/components/LeaderboardCard.vue
src/components/LeaderboardRanking.vue

Give same rank to players with same score

---

src/views/UserProfile.vue

So the profile photo get's shown properly now. For some reason, whenever it's coming from the API, it's a ruby key instead of JS key 🤔 
`user.photoKey || user.photo_key`

Profile fetch user

---

src/components/CornerPoints.vue
src/components/MatchCard.vue
src/components/PredictionChoiceTeam.vue

Prediction Indicator

---

package.json
src/constants/index.js
src/main.js
yarn.lock

Reverts trouni/predictor-vue#140

Revert "Add Google Analytics"

---

src/components/TopNav.vue

removed the useless navbar color

---

src/components/MatchTab.vue
src/components/MatchesGrouping.vue
src/views/Matches.vue

Match tabs

---

src/components/LeaderboardTabs.vue
src/views/Leaderboards.vue

The component is there and functional. Just commented out until the back-end supports it.
Perhaps in the future, we should be fetching the groups instead of hard coding them.
https://user-images.githubusercontent.com/25542223/122319898-423a7400-cf5c-11eb-90d7-f146a7d71721.mov

Leadberboard tabs

---

src/components/FooterNav.vue

replaced home button with back button when logged in

---

src/components/MatchesSubHeader.vue

We're listing games in reverse order anyway and no "bracket-style" like we thought about as well.

not sure it's necessary to have users navigate between stages

---

src/components/PredictionSwiper.vue

⚠️ Needs [this PR](https://github.com/dmbf29/predictor-api/pull/78) in order to work

added location to the match

---

src/views/Home.vue

Fix home page background

---

src/store/modules/competitions.js

hard coded last competition to use World Cup

---

.env.development
src/api/auth.js
src/components/_BaseInputText.vue
src/main.js
src/router/routes.js
src/store/helpers.js
src/store/modules/auth.js
src/store/modules/competitions.js
src/views/ForgotPassword.vue
src/views/Login.vue
src/views/ResetPassword.vue
src/views/UserProfile.vue
tailwind.config.js

- Implement password reset
- Run linter

Add password reset

---

.env.development
src/components/LeaderboardCard.vue
src/components/LeaderboardRanking.vue
src/components/LeaderboardSubHeader.vue
src/store/modules/competitions.js
src/store/modules/leaderboards.js
src/views/Matches.vue
src/views/UserProfile.vue
src/views/layouts/DefaultLayout.vue

| Before  | After  |
|---|---|
| ![image](https://user-images.githubusercontent.com/34345789/202917789-fb14a5a2-52c2-48fa-9531-5a118c40bd02.png)  | ![192 168 0 241_8080_leaderboards(iPhone SE)](https://user-images.githubusercontent.com/34345789/202917737-90ab06d5-bc51-4676-a395-df459cf49c4b.png) |

Update leaderboard style

---

src/views/UserProfile.vue

Unhid upload btn

---

src/components/LeaderboardRanking.vue

⚠️ The PR needs [this PR in the API](https://github.com/dmbf29/predictor-api/pull/96) in be merged and deployed first.
Closes issue #199

added possible points to the user total points

---

src/components/LeaderboardResults.vue
src/components/MatchCard.vue
src/components/MatchPredictions.vue
src/components/MatchPredictionsBar.vue
src/components/MatchesGrouping.vue
src/components/PredictionChoiceDraw.vue
src/components/PredictionChoiceTeam.vue
src/components/ResultCard.vue
src/utils/helpers.js
src/views/Results.vue

Implemented `ResultsCard`, `MatchPredictions` component designs as suggested by @trouni

Leaderboard results pills

---

src/components/MatchPredictions.vue
src/components/ResultCard.vue

on zero sleep so please double check. Looks like this now:

shows red color for incorrect choice

---

src/components/PredictionChoiceTeam.vue
src/components/TeamBadge.vue

displaying extra time and penalty scores if there

---

src/components/LeaderboardRanking.vue

- there might have been a cleaner way, but now getting user own details
- sorry for white space & "" changes, the main addition was line 85-96

User own card #209

---

src/components/_BaseButton.vue
src/views/Login.vue

The plainness of the sign in / sign up was bothering me so just added a logo and moved the button to switch between the 2.
<p float="left">
</p>

Sign in style

---

netlify.toml
src/components/LeaderboardRankingsCard.vue
src/store/modules/users.js
src/views/UserProfile.vue

Current user wasn't being updated. Only getting the cached version
Closes #250

User update

---

netlify.toml
src/components/LeaderboardRankingsCard.vue

photos not properly displayed in production

---

public/index.html

added meta tags for socials

---

src/components/LeaderboardResults.vue

placeholder being shown with games completed

---

src/views/Login.vue

Update error message location that comes from BackEnd
Added a fallback in case location changes and we get an object instead of a string (doesn't check for empty strings🥵)
Ignore the whitespace changes
P.S => Will add a [video in Jira](https://lewagon-alumni.slack.com/archives/C01TJPNBK0C/p1718285069432479?thread_ts=1718284591.818269&cid=C01TJPNBK0C), github can't handle more than 10mb ;/

Updated error message for Login / Register
